doc: Add Module Options to manual

diff --git a/doc/manual/Makefile b/doc/manual/Makefile
--- a/doc/manual/Makefile
+++ b/doc/manual/Makefile
@@ -11,6 +11,7 @@ open: book
 GENERATED = src/schema/resource-schema-v0.gen.md \
 	src/cli/nixops4-resource-runner.md \
 	src/cli/nixops4.md \
+	src/modules/option-docs.gen.md \
 	src/schema/resource-v0/examples/CreateResourceRequest.json \
 	src/schema/resource-v0/examples/CreateResourceResponse.json \
 	src/architecture/cargo-deps.gen.md \
@@ -71,3 +72,25 @@ src/cli/nixops4.md: $(NIXOPS4_EXE)
 src/lib/lib.gen.md: ../../nix/lib/lib.nix Makefile
 	@echo "      NIXDOC" $@
 	@nixdoc --file $< --category "" --description "" --prefix "" --anchor-prefix "" >src/lib/lib.gen.md
+
+src/modules/option-docs.gen.md: $(shell if [[ -z "$$NIXOPS_DEPLOYMENT_OPTION_DOCS_MD" ]]; then \
+			echo deployment-option-docs-md.nix; \
+			echo ../../flake.lock; \
+			find ../../nix -name '*.nix'; \
+		fi)
+	@if [[ -z "$$NIXOPS_DEPLOYMENT_OPTION_DOCS_MD" ]]; then \
+	    if type -p nix >/dev/null; then \
+				rm -f $@; \
+				echo "         NIX" $@; \
+				nix build --extra-experimental-features 'nix-command flakes' \
+				  .#manual-deployment-option-docs-md --out-link $@.tmp; \
+				cat $@.tmp > $@; \
+				rm $@.tmp; \
+			else \
+				echo "Nix not found and NIXOPS_DEPLOYMENT_OPTION_DOCS_MD not set. Can't build option docs."; \
+				exit 1; \
+			fi; \
+		else \
+			echo "        COPY" $@; \
+			cp $$NIXOPS_DEPLOYMENT_OPTION_DOCS_MD $@; \
+		fi
